services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: buriti
      POSTGRES_USER: buriti
      POSTGRES_PASSWORD: buriti
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  redis:
    image: redis:7
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - webnet

  web:
    build: .
    command: sh -c "uv run python manage.py migrate --noinput && uv run python manage.py collectstatic --noinput && uv run python manage.py compress --force && uv run gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: buriti
      POSTGRES_USER: buriti
      POSTGRES_PASSWORD: buriti
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - webnet
  worker:
    build: .
    command: uv run celery -A core worker -l info
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: buriti
      POSTGRES_USER: buriti
      POSTGRES_PASSWORD: buriti
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - webnet

  beat:
    build: .
    command: uv run celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: buriti
      POSTGRES_USER: buriti
      POSTGRES_PASSWORD: buriti
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - webnet

volumes:
  pgdata:

networks:
  webnet:
    driver: bridge
