export const apiEndpoints = {
  register: "/api/register/",
  login: "/api/login/",
  logout: "/api/login/",
  loginWithToken: "/api/token/",
  refreshToken: "/api/token/refresh/",
  csrf: "/api/csrf/",
  basket: "/api/basket/",
  basketAddProduct: "/api/basket/add-product/",
  basketAddVoucher: "/api/basket/add-voucher/",
  basketShippingMethods: "/api/basket/shipping-methods/",
  baskets: "/api/baskets/",
  categories: "/api/categories/",
  checkout: "/api/checkout/",
  checkoutPaymentMethods: "/api/checkout/payment-methods/",
  orders: "/api/orders/",
  options: "/api/options/",
  products: "/api/products/",
  countries: "/api/countries/",
  userProfile: "/api/users/me/",
  userAddresses: "/api/user/addresses/",
  userAddress: (id: number) => `/api/user/addresses/${id}/`,
  userAddressesCount: "/api/user/addresses/count/",
} as const;
